# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Swapnil Raut
title: Fullstack Developer
email: raut.swapnil07@gmail.com
phone: --
# website: Your website (eg. https://google.com)(optional)

# Social links
# twitter_username: jekyllrb
github_username:  svapnilvraut
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: swapnil-raut-782280a5
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: ./profile.jpg
about_content: | # this will include new lines to allow paragraphs

    - <mark>FullStack developer</mark> with more than 9 years' of experience.
    - Extensive hands on experience in Front-End development in <mark>ReactJs</mark>, <mark>Redux</mark>, <mark>JavaScript</mark>, <mark>Angular</mark>, HTML5, CSS3, Bootstrap and related technologies.
    - Back-End development experience in Java, <mark>Spring-Boot</mark>, <mark>Spring-MVC</mark>, Spring-Data, Hibernate.
    - Scripting knowledge in <mark>Shell</mark> scripting, <mark>PERL</mark> scripting and PERL automation.
    - <mark>DevOps</mark> experience in managing configuration management, build and release management and CI-CD tools like <mark>Jenkins</mark> administration and configuration.
    - Proven ability in transforming requirements to designs and solutions for complex enterprise applications.
    - Excellent understanding of requirements and ability to transform them into UI / UX designs and develop the solutions.

# Projects Section
projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
# more_content: | # this will include new lines to allow paragraphs

# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
